// Generated from the official PDF by scripts/process-catalog-matrizes.py.
export const MATRIZES_LOTS = [
  {
    lotNumber: "100",
    animalNames: ["AVIDYA10 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p03.webp"],
    videoUrl: "https://youtube.com/watch?v=c2mrkhJ5pgg",
    animalName: "AVIDYA10 DA MARTENDAL",
  },
  {
    lotNumber: "101",
    animalNames: ["GAMBHIRA15 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p04.webp"],
    videoUrl: "https://youtube.com/watch?v=yRsPazxvCak",
    animalName: "GAMBHIRA15 DA MARTENDAL",
  },
  {
    lotNumber: "102",
    animalNames: ["JANDAIA6 DA MARTENDAL", "LATIFA12 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p05.webp", "/catalogo-matrizes/p06.webp"],
    videoUrl: "https://youtube.com/watch?v=owwTrHMkLSU",
    animalName: "JANDAIA6 DA MARTENDAL + 1 animal",
  },
  {
    lotNumber: "103",
    animalNames: ["MIGRA21 DA MARTENDAL", "PUSHPA3 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p07.webp", "/catalogo-matrizes/p08.webp"],
    videoUrl: "https://youtube.com/watch?v=3U1mH-bAjKU",
    animalName: "MIGRA21 DA MARTENDAL + 1 animal",
  },
  {
    lotNumber: "104",
    animalNames: ["BONITA14 DA MARTENDAL", "JADE4 DA MARTENDAL", "ILHA5 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p09.webp",
      "/catalogo-matrizes/p10.webp",
      "/catalogo-matrizes/p11.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=BU4Z6r5Urb8",
    animalName: "BONITA14 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "105",
    animalNames: ["ADA17 DA MARTENDAL", "JAIRA4 DA MARTENDAL", "HELENA36 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p12.webp",
      "/catalogo-matrizes/p13.webp",
      "/catalogo-matrizes/p14.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=GMv0aWmagd8",
    animalName: "ADA17 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "106",
    animalNames: ["VALA17 DA MARTENDAL", "RECORDACAO8 DA MARTENDAL", "BRANCA18 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p15.webp",
      "/catalogo-matrizes/p16.webp",
      "/catalogo-matrizes/p17.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=hInN_k1MTc0",
    animalName: "VALA17 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "107",
    animalNames: ["ALIQUATA7 DA MARTENDAL", "BANQUETA13 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p18.webp", "/catalogo-matrizes/p19.webp"],
    videoUrl: "https://youtube.com/watch?v=JDgql7izmXM",
    animalName: "ALIQUATA7 DA MARTENDAL + 1 animal",
  },
  {
    lotNumber: "108",
    animalNames: [
      "MESTRANDA2 DA MARTENDAL",
      "NAPATA3 DA MARTENDAL",
      "SAMIRA3 DA MARTENDAL",
      "BATUTA11 DA MARTENDAL",
    ],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p20.webp",
      "/catalogo-matrizes/p21.webp",
      "/catalogo-matrizes/p22.webp",
      "/catalogo-matrizes/p23.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=mG8ntwQ0nDM",
    animalName: "MESTRANDA2 DA MARTENDAL + 3 animais",
  },
  {
    lotNumber: "109",
    animalNames: [
      "BOHEMIA17 DA MARTENDAL",
      "HELENA29 DA MARTENDAL",
      "QUARTUDA4 DA MARTENDAL",
      "TAYGUARA17 DA MARTENDAL",
    ],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p24.webp",
      "/catalogo-matrizes/p25.webp",
      "/catalogo-matrizes/p26.webp",
      "/catalogo-matrizes/p27.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=CHHJZqmm7eE",
    animalName: "BOHEMIA17 DA MARTENDAL + 3 animais",
  },
  {
    lotNumber: "110",
    animalNames: ["NIGODA III", "POLINESIA III"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p28.webp", "/catalogo-matrizes/p29.webp"],
    videoUrl: "https://youtube.com/watch?v=NMVVCSJIF4g",
    animalName: "NIGODA III + 1 animal",
  },
  {
    lotNumber: "111",
    animalNames: ["BATUTA VIII", "HEXA II"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p30.webp", "/catalogo-matrizes/p31.webp"],
    videoUrl: "https://youtube.com/watch?v=UgGK1Z6liDg",
    animalName: "BATUTA VIII + 1 animal",
  },
  {
    lotNumber: "112",
    animalNames: ["FREZA5 DA MARTENDAL", "5900 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p32.webp", "/catalogo-matrizes/p33.webp"],
    videoUrl: "https://youtube.com/watch?v=f3QTomTQ_yI",
    animalName: "FREZA5 DA MARTENDAL + 1 animal",
  },
  {
    lotNumber: "113",
    animalNames: ["ANABEL II", "VICTORIA"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p34.webp", "/catalogo-matrizes/p35.webp"],
    videoUrl: "https://youtube.com/watch?v=vuYlQZhjTGA",
    animalName: "ANABEL II + 1 animal",
  },
  {
    lotNumber: "114",
    animalNames: ["ELITE V", "IRIA VI"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p36.webp", "/catalogo-matrizes/p37.webp"],
    videoUrl: "https://youtube.com/watch?v=UFLK1lTUd10",
    animalName: "ELITE V + 1 animal",
  },
  {
    lotNumber: "115",
    animalNames: ["JACITARA IV", "SAMSARA"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p38.webp", "/catalogo-matrizes/p39.webp"],
    videoUrl: "https://youtube.com/watch?v=7v0l2DL2Igs",
    animalName: "JACITARA IV + 1 animal",
  },
  {
    lotNumber: "116",
    animalNames: ["JUDENGA II"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p40.webp"],
    videoUrl: "https://youtube.com/watch?v=N8vX8vBbSxc",
    animalName: "JUDENGA II",
  },
  {
    lotNumber: "117",
    animalNames: ["CALMA XVII"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p41.webp"],
    videoUrl: "https://youtube.com/watch?v=LMIlOppPWwA",
    animalName: "CALMA XVII",
  },
  {
    lotNumber: "118",
    animalNames: ["DETRA VIII"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p42.webp"],
    videoUrl: "https://youtube.com/watch?v=mEXVxCxeB-4",
    animalName: "DETRA VIII",
  },
  {
    lotNumber: "119",
    animalNames: ["SINTAGMA II"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p43.webp"],
    videoUrl: "https://youtube.com/watch?v=y72dRxsfnBk",
    animalName: "SINTAGMA II",
  },
  {
    lotNumber: "120",
    animalNames: ["SAUDA II *"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p44.webp"],
    videoUrl: "https://youtube.com/watch?v=MYgpFp_ZGl8",
    animalName: "SAUDA II *",
  },
  {
    lotNumber: "121",
    animalNames: ["SINDY2 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p45.webp"],
    videoUrl: "https://youtube.com/watch?v=dimmB3PNQDY",
    animalName: "SINDY2 DA MARTENDAL",
  },
  {
    lotNumber: "122",
    animalNames: ["MIGRA14 FIV", "URUGUAIA9", "PIMENTEIRA"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p46.webp",
      "/catalogo-matrizes/p47.webp",
      "/catalogo-matrizes/p48.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=0Z1cLWfJq4A",
    animalName: "MIGRA14 FIV + 2 animais",
  },
  {
    lotNumber: "123",
    animalNames: ["BALIZA V", "ADA XIII", "ERVEDO"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p49.webp",
      "/catalogo-matrizes/p50.webp",
      "/catalogo-matrizes/p51.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=Zge0TawVPjE",
    animalName: "BALIZA V + 2 animais",
  },
  {
    lotNumber: "124",
    animalNames: ["JHULI2 DA MARTENDAL", "IARA12 DA MARTENDAL", "HORA3 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p52.webp",
      "/catalogo-matrizes/p53.webp",
      "/catalogo-matrizes/p54.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=Yv0pavHcecQ",
    animalName: "JHULI2 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "125",
    animalNames: ["BOHEMIA22 DA MARTENDAL", "PUSPA6 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p55.webp", "/catalogo-matrizes/p56.webp"],
    videoUrl: "https://youtube.com/watch?v=JZbG7zogPN8",
    animalName: "BOHEMIA22 DA MARTENDAL + 1 animal",
  },
  {
    lotNumber: "126",
    animalNames: ["AFRODITE13", "HASUBHA2 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p57.webp", "/catalogo-matrizes/p58.webp"],
    videoUrl: "https://youtube.com/watch?v=mXq9VKju8VA",
    animalName: "AFRODITE13 + 1 animal",
  },
  {
    lotNumber: "127",
    animalNames: ["IRIA12 DA MARTENDAL", "HALACA3 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p59.webp", "/catalogo-matrizes/p60.webp"],
    videoUrl: "https://youtube.com/watch?v=kl7L5J3dWSs",
    animalName: "IRIA12 DA MARTENDAL + 1 animal",
  },
  {
    lotNumber: "128",
    animalNames: ["IDEA7 DA MARTENDAL", "URUGUAIA16 DA MARTENDAL", "CALMA19 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p61.webp",
      "/catalogo-matrizes/p62.webp",
      "/catalogo-matrizes/p63.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=bcylyGIXweY",
    animalName: "IDEA7 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "129",
    animalNames: ["SARARA3 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p64.webp"],
    videoUrl: "https://youtube.com/watch?v=Dy6QHy3Pl4o",
    animalName: "SARARA3 DA MARTENDAL",
  },
  {
    lotNumber: "130",
    animalNames: ["HASSUBE3 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p65.webp"],
    videoUrl: "https://youtube.com/watch?v=DgiDTXqGVkA",
    animalName: "HASSUBE3 DA MARTENDAL",
  },
  {
    lotNumber: "131",
    animalNames: ["SPADELA8 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p66.webp"],
    videoUrl: "https://youtube.com/watch?v=Id2gLdjQBvM",
    animalName: "SPADELA8 DA MARTENDAL",
  },
  {
    lotNumber: "132",
    animalNames: ["URNA5 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p67.webp"],
    videoUrl: "https://youtube.com/watch?v=C7OeLNnJnvM",
    animalName: "URNA5 DA MARTENDAL",
  },
  {
    lotNumber: "133",
    animalNames: ["CALMA22 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p68.webp"],
    videoUrl: "https://youtube.com/watch?v=FeaJyGMAlvA",
    animalName: "CALMA22 DA MARTENDAL",
  },
  {
    lotNumber: "134",
    animalNames: ["JUDENGA7 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p69.webp"],
    videoUrl: "https://youtube.com/watch?v=vLMpB6Ij6do",
    animalName: "JUDENGA7 DA MARTENDAL",
  },
  {
    lotNumber: "135",
    animalNames: ["JUDENGA8 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p70.webp"],
    videoUrl: "https://youtube.com/watch?v=zB0vHKDJS4E",
    animalName: "JUDENGA8 DA MARTENDAL",
  },
  {
    lotNumber: "137",
    animalNames: [
      "HAGAR4 DA MARTENDAL",
      "IRIA16 DA MARTENDAL",
      "DALMA14 DA MARTENDAL",
      "RARAH18 DA MARTENDAL",
    ],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p71.webp",
      "/catalogo-matrizes/p72.webp",
      "/catalogo-matrizes/p73.webp",
      "/catalogo-matrizes/p74.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=LY0WyPmGXb4",
    animalName: "HAGAR4 DA MARTENDAL + 3 animais",
  },
  {
    lotNumber: "138",
    animalNames: ["HORA5 DA MARTENDAL", "ECOLOGIA31 DA MARTENDAL", "JADA2 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p75.webp",
      "/catalogo-matrizes/p76.webp",
      "/catalogo-matrizes/p77.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=O2XkhKQflr0",
    animalName: "HORA5 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "139",
    animalNames: ["LENA2 DA MARTENDAL", "CHIVOLA DA MARTENDAL", "ARLIKA2 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p78.webp",
      "/catalogo-matrizes/p79.webp",
      "/catalogo-matrizes/p80.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=LRo8iOS85L8",
    animalName: "LENA2 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "140",
    animalNames: ["SUSTANCIA2 DA MARTENDAL", "CANDAL7 DA MARTENDAL", "PIMENTEIRA3 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p81.webp",
      "/catalogo-matrizes/p82.webp",
      "/catalogo-matrizes/p83.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=LnSwl_KlRUE",
    animalName: "SUSTANCIA2 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "141",
    animalNames: ["SAMANTACAKRA2 DA MARTENDAL", "2299 DA MARTENDAL", "NOKONA DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p84.webp",
      "/catalogo-matrizes/p85.webp",
      "/catalogo-matrizes/p86.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=dLMWrP8w8TQ",
    animalName: "SAMANTACAKRA2 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "142",
    animalNames: ["PRIMA2 DA MARTENDAL", "ROVETA6 DA MARTENDAL", "ITACHARI8 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p87.webp",
      "/catalogo-matrizes/p88.webp",
      "/catalogo-matrizes/p89.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=lBHkZ2cS0vg",
    animalName: "PRIMA2 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "143",
    animalNames: [
      "UFA2 DA MARTENDAL",
      "JOCASTA DA MARTENDAL",
      "MECA2 DA MARTENDAL",
      "PRANA2 DA MARTENDAL",
    ],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p90.webp",
      "/catalogo-matrizes/p91.webp",
      "/catalogo-matrizes/p92.webp",
      "/catalogo-matrizes/p93.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=OgEcl_I2hqc",
    animalName: "UFA2 DA MARTENDAL + 3 animais",
  },
  {
    lotNumber: "144",
    animalNames: ["AFRODITE18 DA MARTE", "QUELE15 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p94.webp", "/catalogo-matrizes/p95.webp"],
    videoUrl: "https://youtube.com/watch?v=XFOaf05_4VA",
    animalName: "AFRODITE18 DA MARTE + 1 animal",
  },
  {
    lotNumber: "145",
    animalNames: [
      "CAAROLA DA MARTENDAL",
      "PARALELA DA MARTENDAL",
      "DANC46 DA MARTENDAL",
      "MUKHASHALA DA MARTENDAL",
    ],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p96.webp",
      "/catalogo-matrizes/p97.webp",
      "/catalogo-matrizes/p98.webp",
      "/catalogo-matrizes/p99.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=rZ7YoYNlnuY",
    animalName: "CAAROLA DA MARTENDAL + 3 animais",
  },
  {
    lotNumber: "146",
    animalNames: [
      "SORTE2 DA MARTENDAL",
      "TORRADA DA MARTENDAL",
      "GOPALA3 DA MARTENDAL",
      "BATOKA DA MARTENDAL",
      "ADELIA DA MARTENDAL",
    ],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p100.webp",
      "/catalogo-matrizes/p101.webp",
      "/catalogo-matrizes/p102.webp",
      "/catalogo-matrizes/p103.webp",
      "/catalogo-matrizes/p104.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=VoWmRpTi8MA",
    animalName: "SORTE2 DA MARTENDAL + 4 animais",
  },
  {
    lotNumber: "147",
    animalNames: ["SHEIN DA MARTENDAL", "ZILA DA MARTENDAL", "MALOCA DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p105.webp",
      "/catalogo-matrizes/p106.webp",
      "/catalogo-matrizes/p107.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=qlN6lf7C-kw",
    animalName: "SHEIN DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "148",
    animalNames: ["JOJOCA DA MARTENDAL *", "VITORIA DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p108.webp", "/catalogo-matrizes/p109.webp"],
    videoUrl: "https://youtube.com/watch?v=NETbei-TLms",
    animalName: "JOJOCA DA MARTENDAL * + 1 animal",
  },
  {
    lotNumber: "149",
    animalNames: ["LEITOSA II *"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p110.webp"],
    videoUrl: "https://youtube.com/watch?v=CG924JyosTM",
    animalName: "LEITOSA II *",
  },
  {
    lotNumber: "150",
    animalNames: ["NATAMANDIRA3 DA MARTENDAL", "JUDIA2 DA MARTENDAL *"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p111.webp", "/catalogo-matrizes/p112.webp"],
    videoUrl: "https://youtube.com/watch?v=fXW2o52ZVQo",
    animalName: "NATAMANDIRA3 DA MARTENDAL + 1 animal",
  },
  {
    lotNumber: "151",
    animalNames: [
      "FIRE DA MARTENDAL *",
      "ESCURIDAO DA MARTENDAL *",
      "SAPATEIRA3 DA MARTENDAL *",
      "BOLONHA DA MARTENDAL *",
    ],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p113.webp",
      "/catalogo-matrizes/p114.webp",
      "/catalogo-matrizes/p115.webp",
      "/catalogo-matrizes/p116.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=Lk4o4c6Lskg",
    animalName: "FIRE DA MARTENDAL * + 3 animais",
  },
  {
    lotNumber: "153",
    animalNames: ["BARCELONA IV"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p117.webp"],
    videoUrl: "https://youtube.com/watch?v=4_LjUiI2Gyc",
    animalName: "BARCELONA IV",
  },
  {
    lotNumber: "154",
    animalNames: ["SUEDJA13 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p118.webp"],
    videoUrl: "https://youtube.com/watch?v=n2Ac1d0lGPE",
    animalName: "SUEDJA13 DA MARTENDAL",
  },
  {
    lotNumber: "155",
    animalNames: ["ALPINA7 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p119.webp"],
    videoUrl: "https://youtube.com/watch?v=MGC-HU97B3k",
    animalName: "ALPINA7 DA MARTENDAL",
  },
  {
    lotNumber: "156",
    animalNames: ["IDEA8 DA MARTENDAL", "IARA15 DA MARTENDAL", "DANC56 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p120.webp",
      "/catalogo-matrizes/p121.webp",
      "/catalogo-matrizes/p122.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=RhI8PtgDc6w",
    animalName: "IDEA8 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "157",
    animalNames: ["719 FIV DA F MODOTTI"],
    owner: "FAZENDA MODOTTI",
    pages: ["/catalogo-matrizes/p123.webp"],
    videoUrl: "https://youtube.com/watch?v=MXATh9AoVRw",
    animalName: "719 FIV DA F MODOTTI",
  },
  {
    lotNumber: "158",
    animalNames: ["DALILA FIV JLB"],
    owner: "FAZENDA MODOTTI",
    pages: ["/catalogo-matrizes/p124.webp"],
    videoUrl: "https://youtube.com/watch?v=gOCI8OSNwFI",
    animalName: "DALILA FIV JLB",
  },
  {
    lotNumber: "159",
    animalNames: ["SPETSES DA F MODOTTI", "675 FIV DA F MODOTTI"],
    owner: "FAZENDA MODOTTI",
    pages: ["/catalogo-matrizes/p125.webp", "/catalogo-matrizes/p126.webp"],
    videoUrl: "https://youtube.com/watch?v=QCXOF2sOo0Y",
    animalName: "SPETSES DA F MODOTTI + 1 animal",
  },
  {
    lotNumber: "160",
    animalNames: ["702 FIV DA F MODOTTI", "672 FIV DA F MODOTTI"],
    owner: "FAZENDA MODOTTI",
    pages: ["/catalogo-matrizes/p127.webp", "/catalogo-matrizes/p128.webp"],
    videoUrl: "https://youtube.com/watch?v=n-FpSFKabkQ",
    animalName: "702 FIV DA F MODOTTI + 1 animal",
  },
  {
    lotNumber: "161",
    animalNames: ["571 DA F MODOTTI", "607 FIV DA F MODOTTI"],
    owner: "FAZENDA MODOTTI",
    pages: ["/catalogo-matrizes/p129.webp", "/catalogo-matrizes/p130.webp"],
    videoUrl: "https://youtube.com/watch?v=Wv2CJqheCO4",
    animalName: "571 DA F MODOTTI + 1 animal",
  },
  {
    lotNumber: "162",
    animalNames: ["1417 FIV DA F MODOTTI", "1405 FIV DA F MODOTTI"],
    owner: "FAZENDA MODOTTI",
    pages: ["/catalogo-matrizes/p131.webp", "/catalogo-matrizes/p132.webp"],
    videoUrl: "https://youtube.com/watch?v=VIT5QUF7Qo0",
    animalName: "1417 FIV DA F MODOTTI + 1 animal",
  },
  {
    lotNumber: "163",
    animalNames: ["1341 DA F MODOTTI", "1094 FIV DA F MODOTTI"],
    owner: "FAZENDA MODOTTI",
    pages: ["/catalogo-matrizes/p133.webp", "/catalogo-matrizes/p134.webp"],
    videoUrl: "https://youtube.com/watch?v=ixkGdsS-KXY",
    animalName: "1341 DA F MODOTTI + 1 animal",
  },
  {
    lotNumber: "164",
    animalNames: ["592 FIV DA F MODOTTI", "944 DA F MODOTTI", "949 FIV DA F MODOTTI"],
    owner: "FAZENDA MODOTTI",
    pages: [
      "/catalogo-matrizes/p135.webp",
      "/catalogo-matrizes/p136.webp",
      "/catalogo-matrizes/p137.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=ng1mJUUbODw",
    animalName: "592 FIV DA F MODOTTI + 2 animais",
  },
  {
    lotNumber: "165",
    animalNames: ["1146 FIV DA F MODOTTI", "1323 FIV DA F MODOTTI", "1334 FIV DA F MODOTTI"],
    owner: "FAZENDA MODOTTI",
    pages: [
      "/catalogo-matrizes/p138.webp",
      "/catalogo-matrizes/p139.webp",
      "/catalogo-matrizes/p140.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=FXLtA6GaCkA",
    animalName: "1146 FIV DA F MODOTTI + 2 animais",
  },
  {
    lotNumber: "166",
    animalNames: ["1090 FIV DA F MODOTTI", "1230 FIV DA F MODOTTI", "1030 FIV DA F MODOTTI"],
    owner: "FAZENDA MODOTTI",
    pages: [
      "/catalogo-matrizes/p141.webp",
      "/catalogo-matrizes/p142.webp",
      "/catalogo-matrizes/p143.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=OLBF9yBEn90",
    animalName: "1090 FIV DA F MODOTTI + 2 animais",
  },
  {
    lotNumber: "167",
    animalNames: ["BOLADA DA MARTENDAL", "2806 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p144.webp", "/catalogo-matrizes/p145.webp"],
    videoUrl: "https://youtube.com/watch?v=oNah49vvIos",
    animalName: "BOLADA DA MARTENDAL + 1 animal",
  },
  {
    lotNumber: "168",
    animalNames: ["CAIXA IIC", "NIGODA II", "ECOLOGIA XVI"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p146.webp",
      "/catalogo-matrizes/p147.webp",
      "/catalogo-matrizes/p148.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=k6bJI2Asj7g",
    animalName: "CAIXA IIC + 2 animais",
  },
  {
    lotNumber: "170",
    animalNames: ["ILHA4 DA MARTENDAL", "NAYIKA2 DA MARTENDAL", "GRILANTE4 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p149.webp",
      "/catalogo-matrizes/p150.webp",
      "/catalogo-matrizes/p151.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=1p3xInwUmag",
    animalName: "ILHA4 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "171",
    animalNames: ["GOLINHA3 DA MARTENDAL", "MIGRA23 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p152.webp", "/catalogo-matrizes/p153.webp"],
    videoUrl: "https://youtube.com/watch?v=6PI9-WuyE-I",
    animalName: "GOLINHA3 DA MARTENDAL + 1 animal",
  },
  {
    lotNumber: "172",
    animalNames: [
      "AVARANADEVATA13 DA MARTENDAL",
      "SAGARANA11 DA MARTENDAL",
      "MATRIZ6 DA MARTENDAL",
    ],
    owner: "PECUÁRIA MARTENDAL",
    pages: [
      "/catalogo-matrizes/p154.webp",
      "/catalogo-matrizes/p155.webp",
      "/catalogo-matrizes/p156.webp",
    ],
    videoUrl: "https://youtube.com/watch?v=YVNzG3RuK8s",
    animalName: "AVARANADEVATA13 DA MARTENDAL + 2 animais",
  },
  {
    lotNumber: "173",
    animalNames: ["ADA18 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p157.webp"],
    videoUrl: "https://youtube.com/watch?v=h5Wi1utnQPc",
    animalName: "ADA18 DA MARTENDAL",
  },
  {
    lotNumber: "175",
    animalNames: ["JANGADA3 FIV DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p158.webp"],
    videoUrl: "https://youtube.com/watch?v=i3RWsS-leOw",
    animalName: "JANGADA3 FIV DA MARTENDAL",
  },
  {
    lotNumber: "176",
    animalNames: ["COLOMBIA7 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p159.webp"],
    videoUrl: "https://youtube.com/watch?v=ngJbu7P9WbM",
    animalName: "COLOMBIA7 DA MARTENDAL",
  },
  {
    lotNumber: "178",
    animalNames: ["QUEMPA3 FIV DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p160.webp"],
    videoUrl: "https://youtube.com/watch?v=8XTZ1R6teKc",
    animalName: "QUEMPA3 FIV DA MARTENDAL",
  },
  {
    lotNumber: "179",
    animalNames: ["MADURA2  FIV"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p161.webp"],
    videoUrl: "https://youtube.com/watch?v=KTATec_XisA",
    animalName: "MADURA2  FIV",
  },
  {
    lotNumber: "180",
    animalNames: ["COLOMBIA3 FIV DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p162.webp"],
    videoUrl: "https://youtube.com/watch?v=KpeIubyAQYo",
    animalName: "COLOMBIA3 FIV DA MARTENDAL",
  },
  {
    lotNumber: "181",
    animalNames: ["JANGADA FIV DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p163.webp"],
    videoUrl: "https://youtube.com/watch?v=ZIfMsp_jvXg",
    animalName: "JANGADA FIV DA MARTENDAL",
  },
  {
    lotNumber: "182",
    animalNames: ["JURADA FIV FIV DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p164.webp"],
    videoUrl: "https://youtube.com/watch?v=1OIaUg2d0GE",
    animalName: "JURADA FIV FIV DA MARTENDAL",
  },
  {
    lotNumber: "183",
    animalNames: ["228 DA MARTENDAL"],
    owner: "PECUÁRIA MARTENDAL",
    pages: ["/catalogo-matrizes/p165.webp"],
    videoUrl: "https://youtube.com/watch?v=1xd2VA0DQhs",
    animalName: "228 DA MARTENDAL",
  },
  {
    lotNumber: "184",
    animalNames: ["D666 FIV CORB", "D758 FIV CORB"],
    owner: "NELORE CORBETT",
    pages: ["/catalogo-matrizes/p166.webp", "/catalogo-matrizes/p167.webp"],
    videoUrl: "https://youtube.com/watch?v=L0UOei2C-RA",
    animalName: "D666 FIV CORB + 1 animal",
  },
  {
    lotNumber: "185",
    animalNames: ["D845 FIV CORB", "D736 FIV CORB"],
    owner: "NELORE CORBETT",
    pages: ["/catalogo-matrizes/p168.webp", "/catalogo-matrizes/p169.webp"],
    videoUrl: "https://youtube.com/watch?v=dFhR5_GM_Ks",
    animalName: "D845 FIV CORB + 1 animal",
  },
];
