// Generated from the official PDF by scripts/process-catalog-femeas.py.
export const FEMEAS_LOTS = [
  {
    lotNumber: "01",
    animalName: "REM1783M FIV GENETICA ADITIVA",
    owner: "PECUARIA MARTENDAL",
    page: 4,
    pages: ["/catalogo-femeas/p04.webp"],
    videoUrl: "http://youtube.com/watch?v=1wwMqs7c-Ok",
  },
  {
    lotNumber: "02",
    animalName: "IARA15 DA MARTENDAL",
    owner: "PECUARIA MARTENDAL",
    page: 5,
    pages: ["/catalogo-femeas/p05.webp"],
    videoUrl: "http://youtube.com/watch?v=r-wVYvOsXCY",
  },
  {
    lotNumber: "03",
    animalName: "TAYGUARA19 DA MARTENDAL",
    owner: "PECUARIA MARTENDAL",
    page: 6,
    pages: ["/catalogo-femeas/p06.webp"],
    videoUrl: "http://youtube.com/watch?v=nWx3YuFWHuc",
  },
  {
    lotNumber: "04",
    animalName: "DAVITA6 DA MARTENDAL",
    owner: "PECUARIA MARTENDAL",
    page: 7,
    pages: ["/catalogo-femeas/p07.webp"],
    videoUrl: "http://youtube.com/watch?v=eUifa9qZSFc",
  },
  {
    lotNumber: "05",
    animalName: "PIMENTEIRA2 DA MARTENDAL",
    owner: "PECUARIA MARTENDAL",
    page: 8,
    pages: ["/catalogo-femeas/p08.webp"],
    videoUrl: "http://youtube.com/watch?v=v6YsLuhXUFo",
  },
  {
    lotNumber: "06",
    animalName: "RARAH17 DA MARTENDAL",
    owner: "PECUARIA MARTENDAL",
    page: 9,
    pages: ["/catalogo-femeas/p09.webp"],
    videoUrl: "http://youtube.com/watch?v=HZm-bxmLiVY",
  },
  {
    lotNumber: "07",
    animalName: "DETRA19 DA MARTENDAL",
    owner: "PECUARIA MARTENDAL",
    page: 10,
    pages: ["/catalogo-femeas/p10.webp"],
    videoUrl: "http://youtube.com/watch?v=LE-6xGK-uWY",
  },
  {
    lotNumber: "08",
    animalName: "URUGUAIA XIII",
    owner: "PECUARIA MARTENDAL",
    page: 11,
    pages: ["/catalogo-femeas/p11.webp"],
    videoUrl: "http://youtube.com/watch?v=e3_JvR_jmOo",
  },
  {
    lotNumber: "09",
    animalName: "JANGADA2 FIV DA MARTENDAL",
    owner: "PECUARIA MARTENDAL",
    page: 12,
    pages: ["/catalogo-femeas/p12.webp"],
    videoUrl: "http://youtube.com/watch?v=3RLFktGJUro",
  },
  {
    lotNumber: "10",
    animalName: "NEJA2903 FIV V3",
    owner: "AGROPEC. NOVA ALIANÇA",
    page: 13,
    pages: ["/catalogo-femeas/p13.webp"],
    videoUrl: "http://youtube.com/watch?v=RjIEmZcnkiM",
  },
  {
    lotNumber: "11",
    animalName: "BELDADE FIV DA AJSK SANTANA",
    owner: "PAULO MATOS - RANCHO ARAGUAIA",
    page: 14,
    pages: ["/catalogo-femeas/p14.webp"],
    videoUrl: "http://youtube.com/watch?v=pfWSoGpef34",
  },
  {
    lotNumber: "12",
    animalName: "COMETA CONFIANCA",
    owner: "NELORE GALOPEIRA",
    page: 15,
    pages: ["/catalogo-femeas/p15.webp"],
    videoUrl: "http://youtube.com/watch?v=lTaqk9kZzUI",
  },
  {
    lotNumber: "13",
    animalName: "GORA MAT.",
    owner: "ZEDEQUIAS LEITE",
    page: 16,
    pages: ["/catalogo-femeas/p16.webp"],
    videoUrl: "http://youtube.com/watch?v=rGJ-BDvEk2Y",
  },
  {
    lotNumber: "14",
    animalName: "A2885 FIV RG",
    owner: "JACKSON ALEXANDRE - NELORE IMPERADOR",
    page: 17,
    pages: ["/catalogo-femeas/p17.webp"],
    videoUrl: "http://youtube.com/watch?v=uGBt3fY41ZI",
  },
  {
    lotNumber: "15",
    animalName: "1503 FIV DA F MODOTTI",
    owner: "FAZENDA MODOTTI",
    page: 18,
    pages: ["/catalogo-femeas/p18.webp"],
    videoUrl: "http://youtube.com/watch?v=UQPE6ZAiqGM",
  },
  {
    lotNumber: "16",
    animalName: "VASP 1710",
    owner: "NELORE VASP",
    page: 19,
    pages: ["/catalogo-femeas/p19.webp"],
    videoUrl: "http://youtube.com/watch?v=n78xfnl-NbI",
  },
  {
    lotNumber: "17",
    animalName: "ESMERALDA DA PRODUZA",
    owner: "THIAGO WITT",
    page: 20,
    pages: ["/catalogo-femeas/p20.webp"],
    videoUrl: "http://youtube.com/watch?v=D_Z0-xv-FAA",
  },
  {
    lotNumber: "18",
    animalName: "AGZ 3051 FIV",
    owner: "AGROMAZA",
    page: 21,
    pages: ["/catalogo-femeas/p21.webp"],
    videoUrl: "http://youtube.com/watch?v=UjuOGeMZkuM",
  },
  {
    lotNumber: "19",
    animalName: "8458 RIPEC",
    owner: "RENATO INGRACIA - RIPEC",
    page: 22,
    pages: ["/catalogo-femeas/p22.webp"],
    videoUrl: "http://youtube.com/watch?v=wTQDYnNgWIg",
  },
  {
    lotNumber: "20",
    animalName: "B5296 MAT.",
    owner: "GENETICA R1",
    page: 23,
    pages: ["/catalogo-femeas/p23.webp"],
    videoUrl: "http://youtube.com/watch?v=63TvyWUyXTc",
  },
  {
    lotNumber: "21",
    animalName: "JHVM 29735 FIV CAMPARINO",
    owner: "PALMA DE ELBA",
    page: 24,
    pages: ["/catalogo-femeas/p24.webp"],
    videoUrl: "http://youtube.com/watch?v=QECZ_1m03SA",
  },
  {
    lotNumber: "22",
    animalName: "B1356 FIV DA NPDA",
    owner: "FAZENDA PAU D’ALHO",
    page: 25,
    pages: ["/catalogo-femeas/p25.webp"],
    videoUrl: "http://youtube.com/watch?v=vdqHkt1gXTA",
  },
  {
    lotNumber: "23",
    animalName: "ALICE FIV",
    owner: "NELORE JV",
    page: 26,
    pages: ["/catalogo-femeas/p26.webp"],
    videoUrl: "http://youtube.com/watch?v=WCgtm6-wmy0",
  },
  {
    lotNumber: "24",
    animalName: "LUMA MAT.",
    owner: "TIAGO RAVANI - NELORE RAVANI",
    page: 27,
    pages: ["/catalogo-femeas/p27.webp"],
    videoUrl: "http://youtube.com/watch?v=sibmKyC3f10",
  },
  {
    lotNumber: "25",
    animalName: "SARARA2 DA MARTENDAL",
    owner: "PECUARIA MARTENDAL",
    page: 28,
    pages: ["/catalogo-femeas/p28.webp"],
    videoUrl: "http://youtube.com/watch?v=3-O0oknnQHI",
  },
  {
    lotNumber: "26",
    animalName: "HARUMAFE II",
    owner: "PECUARIA MARTENDAL",
    page: 29,
    pages: ["/catalogo-femeas/p29.webp"],
    videoUrl: "http://youtube.com/watch?v=9OHxkOxaxC8",
  },
  {
    lotNumber: "27",
    animalName: "B7902 DA S.NICE",
    owner: "UNIÃO DA VITORIA & GENETICA R1",
    page: 30,
    pages: ["/catalogo-femeas/p30.webp"],
    videoUrl: "http://youtube.com/watch?v=l8We3NEVWNE",
  },
];
