/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeilaoMartendalWeekend2026RouteImport } from './routes/leilao-martendal-weekend-2026'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeilaoMartendalWeekend2026Route =
  LeilaoMartendalWeekend2026RouteImport.update({
    id: '/leilao-martendal-weekend-2026',
    path: '/leilao-martendal-weekend-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leilao-martendal-weekend-2026': typeof LeilaoMartendalWeekend2026Route
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leilao-martendal-weekend-2026': typeof LeilaoMartendalWeekend2026Route
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leilao-martendal-weekend-2026': typeof LeilaoMartendalWeekend2026Route
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leilao-martendal-weekend-2026' | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leilao-martendal-weekend-2026' | '/api/public/track'
  id: '__root__' | '/' | '/leilao-martendal-weekend-2026' | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeilaoMartendalWeekend2026Route: typeof LeilaoMartendalWeekend2026Route
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leilao-martendal-weekend-2026': {
      id: '/leilao-martendal-weekend-2026'
      path: '/leilao-martendal-weekend-2026'
      fullPath: '/leilao-martendal-weekend-2026'
      preLoaderRoute: typeof LeilaoMartendalWeekend2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeilaoMartendalWeekend2026Route: LeilaoMartendalWeekend2026Route,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
