/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsPanelRouteImport } from './routes/leads-panel'
import { Route as LeilaoMartendalWeekend2026RouteImport } from './routes/leilao-martendal-weekend-2026'
import { Route as CatalagoLeilaoMartendalWeekend2026RouteImport } from './routes/catalago.leilao-martendal-weekend-2026'
import { Route as ApiPanelEventsRouteImport } from './routes/api/panel/events'
import { Route as ApiPanelLoginRouteImport } from './routes/api/panel/login'
import { Route as ApiPanelLogoutRouteImport } from './routes/api/panel/logout'
import { Route as ApiPanelSessionRouteImport } from './routes/api/panel/session'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as CatalagoLeilaoMartendalWeekend2026FemeasRouteImport } from './routes/catalago.leilao-martendal-weekend-2026_.femeas'
import { Route as CatalagoLeilaoMartendalWeekend2026MachosRouteImport } from './routes/catalago.leilao-martendal-weekend-2026_.machos'
import { Route as CatalagoLeilaoMartendalWeekend2026MatrizesRouteImport } from './routes/catalago.leilao-martendal-weekend-2026_.matrizes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsPanelRoute = LeadsPanelRouteImport.update({
  id: '/leads-panel',
  path: '/leads-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LeilaoMartendalWeekend2026Route =
  LeilaoMartendalWeekend2026RouteImport.update({
    id: '/leilao-martendal-weekend-2026',
    path: '/leilao-martendal-weekend-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalagoLeilaoMartendalWeekend2026Route =
  CatalagoLeilaoMartendalWeekend2026RouteImport.update({
    id: '/catalago/leilao-martendal-weekend-2026',
    path: '/catalago/leilao-martendal-weekend-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPanelEventsRoute = ApiPanelEventsRouteImport.update({
  id: '/api/panel/events',
  path: '/api/panel/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanelLoginRoute = ApiPanelLoginRouteImport.update({
  id: '/api/panel/login',
  path: '/api/panel/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanelLogoutRoute = ApiPanelLogoutRouteImport.update({
  id: '/api/panel/logout',
  path: '/api/panel/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanelSessionRoute = ApiPanelSessionRouteImport.update({
  id: '/api/panel/session',
  path: '/api/panel/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalagoLeilaoMartendalWeekend2026FemeasRoute =
  CatalagoLeilaoMartendalWeekend2026FemeasRouteImport.update({
    id: '/catalago/leilao-martendal-weekend-2026_/femeas',
    path: '/catalago/leilao-martendal-weekend-2026/femeas',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalagoLeilaoMartendalWeekend2026MachosRoute =
  CatalagoLeilaoMartendalWeekend2026MachosRouteImport.update({
    id: '/catalago/leilao-martendal-weekend-2026_/machos',
    path: '/catalago/leilao-martendal-weekend-2026/machos',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalagoLeilaoMartendalWeekend2026MatrizesRoute =
  CatalagoLeilaoMartendalWeekend2026MatrizesRouteImport.update({
    id: '/catalago/leilao-martendal-weekend-2026_/matrizes',
    path: '/catalago/leilao-martendal-weekend-2026/matrizes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leads-panel': typeof LeadsPanelRoute
  '/leilao-martendal-weekend-2026': typeof LeilaoMartendalWeekend2026Route
  '/catalago/leilao-martendal-weekend-2026': typeof CatalagoLeilaoMartendalWeekend2026Route
  '/api/panel/events': typeof ApiPanelEventsRoute
  '/api/panel/login': typeof ApiPanelLoginRoute
  '/api/panel/logout': typeof ApiPanelLogoutRoute
  '/api/panel/session': typeof ApiPanelSessionRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/catalago/leilao-martendal-weekend-2026/femeas': typeof CatalagoLeilaoMartendalWeekend2026FemeasRoute
  '/catalago/leilao-martendal-weekend-2026/machos': typeof CatalagoLeilaoMartendalWeekend2026MachosRoute
  '/catalago/leilao-martendal-weekend-2026/matrizes': typeof CatalagoLeilaoMartendalWeekend2026MatrizesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leads-panel': typeof LeadsPanelRoute
  '/leilao-martendal-weekend-2026': typeof LeilaoMartendalWeekend2026Route
  '/catalago/leilao-martendal-weekend-2026': typeof CatalagoLeilaoMartendalWeekend2026Route
  '/api/panel/events': typeof ApiPanelEventsRoute
  '/api/panel/login': typeof ApiPanelLoginRoute
  '/api/panel/logout': typeof ApiPanelLogoutRoute
  '/api/panel/session': typeof ApiPanelSessionRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/catalago/leilao-martendal-weekend-2026/femeas': typeof CatalagoLeilaoMartendalWeekend2026FemeasRoute
  '/catalago/leilao-martendal-weekend-2026/machos': typeof CatalagoLeilaoMartendalWeekend2026MachosRoute
  '/catalago/leilao-martendal-weekend-2026/matrizes': typeof CatalagoLeilaoMartendalWeekend2026MatrizesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leads-panel': typeof LeadsPanelRoute
  '/leilao-martendal-weekend-2026': typeof LeilaoMartendalWeekend2026Route
  '/catalago/leilao-martendal-weekend-2026': typeof CatalagoLeilaoMartendalWeekend2026Route
  '/api/panel/events': typeof ApiPanelEventsRoute
  '/api/panel/login': typeof ApiPanelLoginRoute
  '/api/panel/logout': typeof ApiPanelLogoutRoute
  '/api/panel/session': typeof ApiPanelSessionRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/catalago/leilao-martendal-weekend-2026_/femeas': typeof CatalagoLeilaoMartendalWeekend2026FemeasRoute
  '/catalago/leilao-martendal-weekend-2026_/machos': typeof CatalagoLeilaoMartendalWeekend2026MachosRoute
  '/catalago/leilao-martendal-weekend-2026_/matrizes': typeof CatalagoLeilaoMartendalWeekend2026MatrizesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leads-panel'
    | '/leilao-martendal-weekend-2026'
    | '/catalago/leilao-martendal-weekend-2026'
    | '/api/panel/events'
    | '/api/panel/login'
    | '/api/panel/logout'
    | '/api/panel/session'
    | '/api/public/track'
    | '/catalago/leilao-martendal-weekend-2026/femeas'
    | '/catalago/leilao-martendal-weekend-2026/machos'
    | '/catalago/leilao-martendal-weekend-2026/matrizes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leads-panel'
    | '/leilao-martendal-weekend-2026'
    | '/catalago/leilao-martendal-weekend-2026'
    | '/api/panel/events'
    | '/api/panel/login'
    | '/api/panel/logout'
    | '/api/panel/session'
    | '/api/public/track'
    | '/catalago/leilao-martendal-weekend-2026/femeas'
    | '/catalago/leilao-martendal-weekend-2026/machos'
    | '/catalago/leilao-martendal-weekend-2026/matrizes'
  id:
    | '__root__'
    | '/'
    | '/leads-panel'
    | '/leilao-martendal-weekend-2026'
    | '/catalago/leilao-martendal-weekend-2026'
    | '/api/panel/events'
    | '/api/panel/login'
    | '/api/panel/logout'
    | '/api/panel/session'
    | '/api/public/track'
    | '/catalago/leilao-martendal-weekend-2026_/femeas'
    | '/catalago/leilao-martendal-weekend-2026_/machos'
    | '/catalago/leilao-martendal-weekend-2026_/matrizes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadsPanelRoute: typeof LeadsPanelRoute
  LeilaoMartendalWeekend2026Route: typeof LeilaoMartendalWeekend2026Route
  CatalagoLeilaoMartendalWeekend2026Route: typeof CatalagoLeilaoMartendalWeekend2026Route
  ApiPanelEventsRoute: typeof ApiPanelEventsRoute
  ApiPanelLoginRoute: typeof ApiPanelLoginRoute
  ApiPanelLogoutRoute: typeof ApiPanelLogoutRoute
  ApiPanelSessionRoute: typeof ApiPanelSessionRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  CatalagoLeilaoMartendalWeekend2026FemeasRoute: typeof CatalagoLeilaoMartendalWeekend2026FemeasRoute
  CatalagoLeilaoMartendalWeekend2026MachosRoute: typeof CatalagoLeilaoMartendalWeekend2026MachosRoute
  CatalagoLeilaoMartendalWeekend2026MatrizesRoute: typeof CatalagoLeilaoMartendalWeekend2026MatrizesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads-panel': {
      id: '/leads-panel'
      path: '/leads-panel'
      fullPath: '/leads-panel'
      preLoaderRoute: typeof LeadsPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leilao-martendal-weekend-2026': {
      id: '/leilao-martendal-weekend-2026'
      path: '/leilao-martendal-weekend-2026'
      fullPath: '/leilao-martendal-weekend-2026'
      preLoaderRoute: typeof LeilaoMartendalWeekend2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalago/leilao-martendal-weekend-2026': {
      id: '/catalago/leilao-martendal-weekend-2026'
      path: '/catalago/leilao-martendal-weekend-2026'
      fullPath: '/catalago/leilao-martendal-weekend-2026'
      preLoaderRoute: typeof CatalagoLeilaoMartendalWeekend2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panel/events': {
      id: '/api/panel/events'
      path: '/api/panel/events'
      fullPath: '/api/panel/events'
      preLoaderRoute: typeof ApiPanelEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panel/login': {
      id: '/api/panel/login'
      path: '/api/panel/login'
      fullPath: '/api/panel/login'
      preLoaderRoute: typeof ApiPanelLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panel/logout': {
      id: '/api/panel/logout'
      path: '/api/panel/logout'
      fullPath: '/api/panel/logout'
      preLoaderRoute: typeof ApiPanelLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panel/session': {
      id: '/api/panel/session'
      path: '/api/panel/session'
      fullPath: '/api/panel/session'
      preLoaderRoute: typeof ApiPanelSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalago/leilao-martendal-weekend-2026_/femeas': {
      id: '/catalago/leilao-martendal-weekend-2026_/femeas'
      path: '/catalago/leilao-martendal-weekend-2026/femeas'
      fullPath: '/catalago/leilao-martendal-weekend-2026/femeas'
      preLoaderRoute: typeof CatalagoLeilaoMartendalWeekend2026FemeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalago/leilao-martendal-weekend-2026_/machos': {
      id: '/catalago/leilao-martendal-weekend-2026_/machos'
      path: '/catalago/leilao-martendal-weekend-2026/machos'
      fullPath: '/catalago/leilao-martendal-weekend-2026/machos'
      preLoaderRoute: typeof CatalagoLeilaoMartendalWeekend2026MachosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalago/leilao-martendal-weekend-2026_/matrizes': {
      id: '/catalago/leilao-martendal-weekend-2026_/matrizes'
      path: '/catalago/leilao-martendal-weekend-2026/matrizes'
      fullPath: '/catalago/leilao-martendal-weekend-2026/matrizes'
      preLoaderRoute: typeof CatalagoLeilaoMartendalWeekend2026MatrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadsPanelRoute: LeadsPanelRoute,
  LeilaoMartendalWeekend2026Route: LeilaoMartendalWeekend2026Route,
  CatalagoLeilaoMartendalWeekend2026Route:
    CatalagoLeilaoMartendalWeekend2026Route,
  ApiPanelEventsRoute: ApiPanelEventsRoute,
  ApiPanelLoginRoute: ApiPanelLoginRoute,
  ApiPanelLogoutRoute: ApiPanelLogoutRoute,
  ApiPanelSessionRoute: ApiPanelSessionRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  CatalagoLeilaoMartendalWeekend2026FemeasRoute:
    CatalagoLeilaoMartendalWeekend2026FemeasRoute,
  CatalagoLeilaoMartendalWeekend2026MachosRoute:
    CatalagoLeilaoMartendalWeekend2026MachosRoute,
  CatalagoLeilaoMartendalWeekend2026MatrizesRoute:
    CatalagoLeilaoMartendalWeekend2026MatrizesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
